### ISSUE TITLE
Event volunteer signup sheet

### ISSUE THREAD

**Issue by thebestmensch** [open-austin/org#368]
@open-austin/leadership does it make sense to bring something like this back for folks that want to help? We had a few volunteers at our last meetup. 

Here's the old doc: https://docs.google.com/spreadsheets/d/1B472jCRq0W5ag4TNmR8xVapd7n863luPTuNZOx_YG8Q/edit?usp=sharing

Maybe @mscarey can touch on why it didn't work last time?

**Comment by mateoclarke** [comment]
This really helped us in the past in my opinion. I'd vote to bring it back if would could get somebody to wrangle volunteers.

**Comment by mscarey** [comment]
Yeah, I think it was working well until the number of people helping out dipped too low, which probably made it seem unnecessary to coordinate through the form. But I think we have enough people that the form will be helpful again.

**Comment by JMensch** [comment]
Spoke to Vickie at the library meetup. Sounds like this probably fell off in the past due to lack of maintenance. Mentioned a slack bot to post this. Some potential ideas to streamline this:

- Bot to post signup sheet to iced-coffee slack channel
- Differentiate event tasks that need to happen beforehand (orderering pizza) vs tasks that can be picked up adhoc (sign in desk)

Things to consider:
- Who on the leadership team going to coordinate this? Any way to automate?
- Do we need a volunteer lead? 

Next steps: Get feedback from volunteers on old sheet, ideas for new process that works for htem.
